import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";

const myCustomFont = localFont({
  src: "../../public/fonts/font.ttf",
  variable: "--font-cal-sans",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myCustomFont.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
